### ISSUE TITLE
fairplay

### ISSUE THREAD

**Issue by whm04** [inka-pallycon/html5-player-drm-samples#1]
how to get fairplayToke  if you have fairplayCertUri  ?

**Comment by daniel-inka** [comment]
Hi, 
You need to sign up on [PallyCon.com](https://login.pallycon.com/join.htm/?lang=en) to get you DRM tokens (for FairPlay, Widevine, PlayReady) as well as the cert Uri. 
You can get the test tokens on our [DevConsole](https://sample.pallycon.com/dev/devconsole/customData.do?lang=en#create-token), or create them on your server using our [guide](https://pallycon.com/docs/en/multidrm/license/license-token/) and [samples](https://pallycon.com/docs/en/multidrm/getting-started/downloads/#multi-drm-token-integration-sample).

Please sign up for a free trial for the next step.
