### ISSUE TITLE
Not working in Microsoft Edge

### ISSUE THREAD

**Issue by Hakai-Shin** [inka-pallycon/html5-player-drm-samples#10]
Facing issue in microsoft edge

[12317][Stream] Error sending update() message! InvalidStateError

![image](https://user-images.githubusercontent.com/54961206/218065644-587730ad-fce7-47d3-8d4d-6117bb3f3936.png)

**Comment by daniel-inka** [comment]
Hi,

Sorry for the delayed reply on the issue.

For better technical support, we have a [Helpdesk service](https://pallycon.zendesk.com) as our primary support channel.
We are not managing the Github issues anymore, and will remove the functionality from all of our repositories.

Please create a ticket on the helpdesk instead if you haven't yet.

Thanks,
Daniel
