### ISSUE TITLE
Not working in chrome on m2 macbook air devices

### ISSUE THREAD

**Issue by AlskaPark** [inka-pallycon/html5-player-drm-samples#14]
The running environment is as shown below and I get the error as shown in the screenshot.
Model: MacBook Air M2, 2022
MacOS: Ventura 13.4.1 (c)
Browser: Google Chrome 116.0.5845.187 (official build) (arm64)
Additionally, we've seen the same error on other arm based Mac devices.
![스크린샷 2023-09-26 오전 11 19 51](https://github.com/inka-pallycon/html5-player-drm-samples/assets/9472921/b9c8c81b-e1ee-4e4c-87e3-6112c0f34d61)
![스크린샷 2023-09-26 오전 11 19 10](https://github.com/inka-pallycon/html5-player-drm-samples/assets/9472921/5861588c-8b6a-41de-ba5f-079ea5cafcad)

**Comment by daniel-inka** [comment]
Hi,

Sorry for the delayed reply on the issue.

For better technical support, we have a [Helpdesk service](https://pallycon.zendesk.com) as our primary support channel.
We are not managing the Github issues anymore, and will remove the functionality from all of our repositories.

Please create a ticket on the helpdesk instead if you haven't yet.

Thanks,
Daniel
