### ISSUE TITLE
what are token rules or license rules in licence token generation ?

### ISSUE THREAD

**Issue by svhemanth** [inka-pallycon/html5-player-drm-samples#3]

**Comment by jinseok-Noh** [comment]
@svhemanth 

Sorry for the late reply. 
It is difficult to check the menu of github issues. 

Pallycon License Token Guide : 
https://pallycon.com/docs/en/multidrm/license/license-token/

If you have any further questions, please contact the help desk.
https://pallycon.zendesk.com/hc/en-us
